from itertools import islice
import os

def reverse_comp(s):
    s=s.upper()
    comp=''.join(map(lambda x:dict(zip('ATCGN','TAGCN'))[x]  ,s))
    return comp[::-1]

def check_file_reverse_comp(f1,f2):
    nonrevcount = 0
    for l1,l2 in islice(zip(f1,f2),1,800,4):
        l1_ = l1.decode('utf-8')
        l2_=l2.decode('utf-8')
        if reverse_comp(l1_.strip())!=l2_.strip():
            nonrevcount+=1
    if nonrevcount>50:
        return False
    return True



def file_blocks(files, size=65536):
    while True:
        b = files.read(size)
        if not b: break
        yield b


def file_generator(f1,f2):
    with open(f1,'rt') as f, open(f2,'rt') as r:
        for line,rev in zip(islice(f,1,None,4),islice(r,1,None,4)):
            line=line.strip()
            rev=rev.strip()

            yield line,rev

def file_generator_raw(f1,f2):
    with open(f1,'rt') as f, open(f2,'rt') as r:
        for line,rev in zip(islice(f,1,None),islice(r,1,None)):
            line=line.strip()
            rev=rev.strip()
            yield line,rev

def totalread(f1):
    with open(f1, 'rt') as f:
        fb1 = file_blocks(f)
        totalread = sum(bl.count("\n") for bl in fb1)
    return totalread/4

totalread(f)
totalread(r)

f="/Users/hui/Downloads/N8A-C-R8CDF_S1_L001_R1_001.fastq"
r="/Users/hui/Downloads/N8A-C-R8CDF_S1_L001_R2_001.fastq"

fg = file_generator_raw(f,r)

fgs = file_generator(f,r)
len(itfp)

count = 0
revcomp = 0
for i in range(100):
    l1,l2 = next(fgs)
    l2r = reverse_comp(l2)
    itfpindex = (itfp in l1) and l1.index(itfp)
    krpcindex = (krpc in l1) and l1.index(krpc)
    itfpindex1 = (itfp in l2r) and l2r.index(itfp)
    krpcindex1 = (krpc in l2r) and l2r.index(krpc)
    Fstrand = l1[itfpindex+len(itfp):krpcindex]
    Rstrandrc = l2r[itfpindex1+len(itfp):krpcindex1]
    print(Fstrand)
    print(Rstrandrc)
    print('+++++++++++'*3)
    # if not itfpindex:
    #     count += 1
    #     l1_p = l1[2:10]
    #     if reverse_comp(l1_p) not in l2r:
    #         revcomp +=1



count/1000

revcomp/1000


    #     print(l1)
    # print("S{:>3d}; Forward F {} ; R {}".format(i,itfpindex,krpcindex))
    # print("S{:>3d}; Reverse F {} ; R {}".format(i,itfpindex1,krpcindex1))


for i in range(80):
    l1,l2=next(fg)
    print(l1+'\n'+l2)


a=(next(fg))


a[0]
krp ="TTCACGGTAGCACGCATAGG"
krpc = 'CCTATGCGTGCTACCGTGAA'
itfp = "GATGTGAGTGTGTGACGATG"
itfpc='CATCGTCACACACTCACATC'

reverse_comp("GATGTGAGTGTGTGACGATG")

AAAGGATAACACTATTTAGGTAGTAGCGCGAGATTCACGGTAGCACGCATAGGGTAACCCAGTACATTGGACCTAACTTTCAAGGCAGGAGGACATCGTCACACACTCACATCCGAGTAATGCGCTTACGATACGTACCAGTTCGCGCGN
NCGCGCGAACTGGTACGTATCGTAAGCGCATTACTCGGATGTGAGTGTGTGACGATGTCCTCCTGCCTTGAAAGTTAGGTCCAATGTACTGGGTTACCCTATGCGTGCTACCGTGAATCTCGCGCTACTACCTAAATAGTGTTATCCTTT
TTGAAAGGATAACACTATTTAGGTAGTAGCGCGAGATTCACGGTAGCACGCATAGGGTAACCCAGTACATTGGACCTAACTTTCAAGGCAGGAGGACATCGTCACACACTCACATCCGAGTAATGCGCTTACGATACGTACCAGTTCGCG
+
+
#8ACCGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGFGGGGGGGFGGGGGGGGGGGGGFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGEFFGGGGGGGGGGGG
CCCCCGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGFFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG9FGGGGGGGGGGGGGGGGGGGGGGGG
@M06673:6:000000000-CMWK5:1:1101:10207:1000 1:N:0:1
@M06673:6:000000000-CMWK5:1:1101:10207:1000 2:N:0:1

     CCGCAACGCAGCGACGAGCACGAGAGCGGTCAGTAGCAATCCAAACTTTGTTACTCGTCAGAAAATCGAAATCATCTTCGGTTAAATCCAAAACGGCAGAAGCCTGAATGAGCTTAATAGAGGCCAAAGCGGTCTGGAAACGTACGGATTN
NAATCCGTACGTTTCCAGACCGCTTTGGCCTCTATTAAGCTCATTCAGGCTTCTGCCGTTTTGGATTTAACCGAAGATGATTTCGATTTTCTGACGAGTAACAAAGTTTGGATTGCTACTGACCGCTCTCGTGCTCGTCGCTGCGTTGCGG
CTGCGCGTACACGCAAGGTAAACGCGAACAATTCAGCGGCTTTAACCGGACGCTCGACGCCATTAATAATGTTTTCCGTAAATTCAGCGCCTTCCATGATGAGACAGGCCGTTTGAATGTTGACGGGATGAACATAATAAGCAATGACGG
+
+
#8A8A@BFFGEFDG<FFGGGGGE@@FCGFFGGE,FCC<EFGFGGGGGGGGCDFGGGG:BF@FGGGGGGGECE@CFGCDFAEGEDCF9ADEFGGGGEGGFFGFFGFD<?FAFEFGFCE?FG<CED@F+@=F?B=F+,4@F:F7=>>@BE+3+
@@CCCGGEEEC@F7@FGFC@FFEFGGGEFCEFFCFEGEEGCCFGFGGGD+FEF7FGG7FEGGEGEFFFEFGD<B?<<:FGGGBAFGE9=:FG>E@?EFFGGG<FGGFFG7=@+B>D<C<5E9FFGE@CGE,87@DCAFFFC9FC>@CCBE
@M06673:6:000000000-CMWK5:1:1101:17073:1001 1:N:0:1
@M06673:6:000000000-CMWK5:1:1101:17073:1001 2:N:0:1
  TACTGTAGACATTTTTACTTTTTATGTCCCTCATCGTCACGTTTATGGTGAACAGTGGATTAAGTTCATGAAGGATGGTGTTAATGCCACTCCTCTCCCGACTGTTAACACTACTGGTTATATTGACCATGCCGCTTTTCTTGGCACGATN
NATCGTGCCAAGAAAAGCGGCATGGTCAATATAACCAGTAGTGTTAACAGTCGGGAGAGGAGTGGCATTAACACCATCCTTCATGAACTTAATCCACTGTTCACCATAAACGTGACGATGAGGGACATAAAAAGTAAAAATGTCTACAGTA
TTCCTTGCTGGTCAGATTGGTCGTCTTATTACCATTTCAACTACTCCGGTTATCGCTGGCGACTCCTTCGAGATGGACGCCGTTGGCGCTCTCCGTCTTTCTCCATTGCGTCGTGGCCTTGCTATTGACTCTACTGTAGACATTTTTACTT
+
+
#8ACCGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGFGGGGGGDGGGGGDGGGGGGGGGGGGDGGGGGGGDGFFFGGGGGGFGFGGGGGGGGGGGGGGGGGGGGGGGGGDGGFFGGGGGGGGGGGFGGGGBFFGGFG9C
CCCCCGGGGGGDGFGFGGGGGGGCCGGGGGGGGGGGGGGGGGGEEFGECCFGGGGGGEGGGGGGGGGGGGGGGGFFGE:FGGGGGGGGGGGGGGGGGGGGGDFFEFFEGGGEEFGEGGFGFGFGGGGGGGFGFFFGCGGGEGGGGGGFFDF
@M06673:6:000000000-CMWK5:1:1101:21863:1002 1:N:0:1
@M06673:6:000000000-CMWK5:1:1101:21863:1002 2:N:0:1
NGTGTAGCGAACTGCGATGGGCATACTGTAACCATAAGGCCACGTATTTTGCAAGCTATTTAACTGGCGGCGATTGCGTACCCGACGACCAAAATTAGGGTCAACGCTACCTGTAGGAAGTGTCCGCATAAAGTGCACCGCATGGAAATGA
GCGTGACTATTTTCGTGATATTGGTCGTATGGTTCTTGCTGCCGAGGGTCGCAAGGCTAATGATTCACACGCCGACTGCTATCAGTATTTTTGTGTGCCTGAGTATGGTACAGCTAATGGCCGTCTTCATTTCCATGCGGTGCACTTTATG
+
+
#8A6A<C<@@F@CC6@:F;FFACFGDE@FGA6FG,FGGEF@@C@F@CFAGGEFDFCE@<F6FCGFC<<++7@6FCF9?@B+49>F:EGEE:<4,54C<?,:9AF,=>44=FFGGGE?<?FFGCDGE@:>FDD?CB97DC:FC+@<F<FG=F
CC9AB;FGCE<CFF:FEG,66@@FCFCGC@FCFFEAF<FF9@6@FGEEG@@B@FGGFGFGCC<GGA,E@@@FGC@>>><?EGGGFEDGGF9FCGGFEF?FG8?FAFFFGAFG<<FE?F<?=<:FG@FD<FE<AFDE,AB+86@FE<4:8E9
@M06673:6:000000000-CMWK5:1:1101:10143:1002 1:N:0:1
@M06673:6:000000000-CMWK5:1:1101:10143:1002 2:N:0:1
NGGGAGTAAGCTTGCGGCCTGTGACGGGGTCCGGAGAGATGTGAGTGTGTGACGATGTAAGTTCGAGAACTGACCTTAAACCAGTGTACAGGGATACCCTATGCGTGCTACCGTGAATCTCGCGCTACCAAGCCAGTGCCGCATTCGCG
TCAGCGCGAATGCGGCACTGGCTTGGTAGCGCGAGATTCACGGTAGCACGCATAGGGTATCCCTGTACACTGGTTTAAGGTCAGTTCTCGAACTTACATCGTCACACACTCACATCTCTCCGGACCCCGTCACAGGCCGCAAGCTTACTC
+
+
#8BCCGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
CCCCCGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGFGGGGGGGGGGGGGGFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGEGGGGGGGGGGG
@M06673:6:000000000-CMWK5:1:1101:15495:1003 1:N:0:1
@M06673:6:000000000-CMWK5:1:1101:15495:1003 2:N:0:1
NGCACTTGTGTTCGTCCCGAGCCAGGAAAATTCAGAAGATGTGAGTGTGTGACGATGCCTATGCGTGCTACCGTGAATCTCGCGCCTTACGGGGGCTGCACCAACTAGAGAGTAGATCGGAAGAGCACACGTCTGAACTCCAGTCACCGG
ACTCTCTAGTTGGTGCAGCCCCCGTAAGGCGCGAGATTCACGGTAGCACGCATAGGCATCGTCACACACTCACATCTTCTGAATTTTCCTGGCTCGGGACGAACACAAGTGCGAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGAT
+
+
#8ACCGGGGFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGFFGGGGGGGGGGGGCGGGGGGGEGFFEGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGCFGGGGGGGGGGGGGGCEFEGEGGCGFGGGGGFGGGGGGGAFFFGGGGGGC
CCCCCGGGGGGGGGGGFFGFGGGGGGGGFGGGEGGGGGGGGFGFGGGCFGGCEGGCGGGGGGGGGGGGGGGAFGCFGGGGGGFFFGFGFGGFGGGGGGGEGGGGGGGGGGFGGGGGFFGDCEEFFFEFFG:CFAFFG,FFFCFGFDFCAF
@M06673:6:000000000-CMWK5:1:1101:22255:1003 1:N:0:1
@M06673:6:000000000-CMWK5:1:1101:22255:1003 2:N:0:1
NTCAGCACCAACAGAAACAACCTGATTAGCGGCGTTGACAGATGTATCCATCTGAATGCAATGAAGAAAACCACCATTACCAGCATTAACCGTCAAACTATCAAAATATAACGTTGACGATGTAGCTTTAGGTGTCTGTAAAACAGGTGC
TGTGACCGTTTATCGCAATCTGCCGACCACTCGCGATTCAATCATGACTTCGTGATAAAAGATTGAGTGTGAGGTTATAACGCCGAAGCGGTAAAAATTTTAATTTTTGCCGCTGAGGGGTTGACCAAGCGAAGCGCGGTAGGTTTTCTG
+
+
#8BCCGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
CCCCCFGGGGGGGGGGGEGGFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGFEGGGGGGGGFGFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGFGGGGGGGGGGGGGGGGGGGGGEGFGGG<FFGGGG
@M06673:6:000000000-CMWK5:1:1101:10232:1003 1:N:0:1
@M06673:6:000000000-CMWK5:1:1101:10232:1003 2:N:0:1
NCTTATTACCCTTCTGAATGTCACGCTGATTATTTTGACTTTGAGCGTATCGAGGCTCTTAAACCTGCTATTGAGGCTTGTGGCATTTCTACTCTTTCTCAATCCCCAATGCTTGGCTTCCATAAGCAGATGGATAACCGCATCAAGCT
TTCGTCCCCTTCGGGGCGGTGGTCTATAGTGTTATTAATATCAAGTTGGGGGAGCACATTGTAGCATTGTGCCAATTCATCCATTAACTTCTCAGTAACAGATACAAACTCATCACGAACGTCAGAAGCAGCCTTATGGCCGTCAACATA
+
+
#8ABCGGF@C<CECFGGGGGGGEDGCGGCAFD<FGFG@CFFGGGGDGGGGFCCGC:FFGGGGEFFGCFFGGGG,6E<CFGGGGGGEGG9FFFE<<FGG96F?FG@<A?69:F?FG7<FF?FFGFDEGF<,EFAFGGCEFGGGGGGDDC,
CCCCCG;@FFGADFGEGGD@FE@<@@@6FEGCCFCC66CF9E<,6C6<6F:6+769FFG96CEGG<E<C?CAFCEGFACE99,C<FFGGDDGGDFGCGDAF<5EGG<FGGGG,55EFCGGC?=FC<F?FEFF@FGGEAFGFG=>@FEEGF
@M06673:6:000000000-CMWK5:1:1101:10276:1003 1:N:0:1
@M06673:6:000000000-CMWK5:1:1101:10276:1003 2:N:0:1
NTGTTCCCGTGAGAGAGTCCACGTCTTAAATTACTCGGATGTGAGTGTGTGACGATGCCACAGTAAATTTGATTAGTCGTGTGAAGAAAACTGTCAACCTATGCGTGCTACCGTGAATCTCGCGCAGACAGTTCGATGACTAGCCACTGG
GGGCCAGTGGCTAGTCATCGAACTGTCTGCGCGAGATTCACGGTAGCACGCATAGGTTGACAGTTTTCTTCACACGACTAATCAAATTTACTGTGGCATCGTCACACACTCACATCCGAGTAATTTAAGACGTGGACTCTCTCACGGGAA
+
+
#8ACCFGEGFGGGFGGGGGFGGGGGGGGGGGGGG9FGDGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGFGGDEGGGGGGGGGGEFGGGGFGFGDFEEFFGGGGGGGFGFGGGGGGGGGGGGGGGGGGFGGGGGEEGEFGGGG
CCCCCGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGDGGGGGGGGGGGGGGGFGGGGGGFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGFGGGGGGGGDGGGGGGGFGGGGGGGG
@M06673:6:000000000-CMWK5:1:1101:11735:1005 1:N:0:1
@M06673:6:000000000-CMWK5:1:1101:11735:1005 2:N:0:1
NGCGTTATAACCTCACACTCAATCTTTTATCACGAAGTCATGATTGAATCGCGAGTGGTCGGCAGATTGCGATAAACGGTCACATTAAATTTAACCTGACTATTCCACTGCAACAACTGAACGGACTGGAAACACTGGTCATAATCATGGT
TTCAGTACCTTAACGCTAAAGGTGCTTTGACTTATACCGATATTGCTGGCGACCCTGTTTTGTATGGCAACTTGCCGCCGCGTGAAATTTCTATGAAGGATGTTTTCCGTTCTGGTGATTCGTCTAAGAAGTTTAAGATTGCTGAGGGTCA
+
+
#8ACCFCFGGGG9EGDFGGGGGGGFGEGGGGGGGGGGCDFGGGDGGGGGGGGGGEGGGFGGGDEGGGFGDFGGFEFFEGGGGGGGGGGGGGGGGGGGFGGGGGGGGGGGFFGAFEFGGGGGFGGGGEGEGCFCFGGGFFFFFGGGGGFGGF
-ACCCFFGGGGGGGGGG;FGGFFFGGFGGGGGGGGGGGEGEDEFFGGFCECG@F7FF<CF<FEEFFG?EFGDFE<F@CF@F@=FEFAC<EF9?DF9F9FFGGFGF=FGGGFGDGFGG9FFGF,FE7F,C,=@FF?FF<EFGCFFF8DEGG8
@M06673:6:000000000-CMWK5:1:1101:12706:1005 1:N:0:1
@M06673:6:000000000-CMWK5:1:1101:12706:1005 2:N:0:1
NAAGCCGTCCACCCTGTGCCCAAGGGTTGCGCTCATTGATGTGAGTGTGTGACGATGCCTATGCGTGCTACCGTGAATCTCGCGCTTTTAATTGTGTCAAGGTTAGGTCGGTGAGATCGGAAGAGCACACGTCTGAACTCCAGTCACCGG
CACCGACCTAACCTTGACACAATTAAAAGCGCGAGATTCACGGTAGCACGCATAGGCATCGTCACACACTCACATCAATGAGCGCAACCCTTGGGCACAGGGTGGACGGCTTCAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGAT
+
+
#88CCGFCC:FEEGDEGGFGFGDFFCGGFFF@:FCGD,FEFGFDA<EFEFFGACGDGGCAFGGDEFF@DAFGGGFF@FGGGGDGDEEFGCGFG<EFGGFFG8EFGFFGGEEGE+FCFFDDGDEFGGGGGGGG@EFGFFF9FCFFEFGECC
CCCC@FEEGFAFGGGFGDGGGCDGGFGAFGGEGG+FFAE9FFDDGCGFFBEFGG,EFGGFDG<DEGGGGFFGGGGGFFGFFECGGD@CFGGGGGGD8FGCFGGGED=FC7CFAF?FAEGGEEGGGGEEFE=CGGFGGCFGGFDFFEGEFG
@M06673:6:000000000-CMWK5:1:1101:11951:1005 1:N:0:1
@M06673:6:000000000-CMWK5:1:1101:11951:1005 2:N:0:1
NACAATGACAAATCTGTCCACGGAGTGCTTAATCCAACTTACCAAGCTGGGTTACGACGCGACGCCGTTCAACCAGATATTGAAGCAGAACGCAAAAAGAGAGATGAGATTGAGGCTGGGAAAAGTTACTGTAGCCGACGTTTTGGCGGCG
AAGGATAGGTCGCATTTTCTCATTTTCCGCCAGCAGTCCACTTCGATTTAATTCGTAAACAAGCAGTAGTAATTCCTGCTTTATCACGATAATTTTTCGACTCATCAGAAATATCCGAAAGTGTTAACTTCTGCGTCATGGAAGCGATAAA
+
+
#8A@CGGFGGGFGGGFGFGGDCGEGGGGGAFCFGGGGDFGGGGGGG@FGFGGEGGGGG:CEECEDGGGGCFGGG7FF<FGGGGGGGGGGGGGGFDGCDFFEFFAAF?ECCEFGGG@EB:?=<FFEGFGGEABF9FGGGDECEFDFFGGGGF
CC--8@-;-C<@+6BCCGGGAECGGG<9FGCEGGG<FFGGGFFFECFCFC@EFCGFGGD<FGGF@ECF@ED<C<C@FA8EFA6CA9,BFFGGGGCG9CFDFFGGGDA=ABA?9,9EFG7C+95EFGFF,CAF9F@FEF<EFGEFG>FA+?A
@M06673:6:000000000-CMWK5:1:1101:22085:1006 1:N:0:1
@M06673:6:000000000-CMWK5:1:1101:22085:1006 2:N:0:1
NATATATTTTCGAAACGATTGTTCTTTAAATTACTCGGATGTGAGTGTGTGACGATGCCACAGTAAATTTGATTAGTCGTGTGAAGAAAACTGTCAACCTATGCGTGCTACCGTGAATCTCGCGCCGAACAAGAAGATTTTAAATTAAGTG
ATCACTTAATTTAAAATCTTCTTGTTCGGCGCGAGATTCACGGTAGCACGCATAGGTTGACAGTTTTCTTCACACGACTAATCAAATTTACTGTGGCATCGTCACACACTCACATCCGAGTAATTTAAAGAACAATCGTTTCGAAAATATA
+
+
#8BCCGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
CCCCCGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGF
@M06673:6:000000000-CMWK5:1:1101:19720:1006 1:N:0:1
@M06673:6:000000000-CMWK5:1:1101:19720:1006 2:N:0:1
NGCGATTTCATAGTGGAGGCCTCCAGCAATCTTGAACACTCATCCTTAATACCTTTCTTTTTGGGGTAATTATACTCATCGCGAATATCCTTAAGAGGGCGTTCAGCAGCCAGCTTGCGGCAAAACTGCGTAACCGTCTTCTCGTTCTCTA
CGCATCAAGCTCTTGGAAGAGATTCTGTCTTTTCGTATGCAGGGCGTTGAGTTCGATAATGGTGATATGTATGTTGACGGCCATAAGGCTGCTTCTGACGTTCGTGATGAGTTTGTATCTGTTACTGAGAAGTTAATGGATGAATTGGCA
+
+
#8ACCGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGFGGFGGGGGGGGGGGGGGGGGGFGGGGDFGGGGGGGGGGGGGGDGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGFGGGGGGGGGGF
@CCCC@@ECF<<@EGGFGGGG@FCFFGGFGG<CFG@EDFGCGFGGGECFGGFGGGEGGGCFGGGCFAEDFGFGGGGGGDC+@@@<6FFFGGDFGCFFGFGEGGGFEEFFDFFAFEGCEFGCFGFGGGFFFGEEFDGF<<FFGGGDFEDGG
@M06673:6:000000000-CMWK5:1:1101:10351:1006 1:N:0:1
@M06673:6:000000000-CMWK5:1:1101:10351:1006 2:N:0:1
NTGTCTAAGTTTGCTGTGTCACCTCAACCCGCTCATTGATGTGAGTGTGTGACGATGCCTATGCGTGCTACCGTGAATCTCGCGCTTTATCTGTCTATTATAGTTTAGCTCGTAGATCGGAAGAGCACACGTCTGAACTCCAGTCACCGG
ACGAGCTAAACTATAATAGACAGATAAAGCGCGAGATTCACGGTAGCACGCATAGGCATCGTCACACACTCACATCAATGAGCGGGTTGAGGTGACACAGCAAACTTAGACAAAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGAT
+
+
#8A@CGGFGGGGGGGFGGGGGGGFGGFFGGGGEGGGGFFGGGCGFGGGGGGGGGGGGGGGGGFFEGEGGGGGGFGGGGGFGGGGGGGGGGGFGGGGGGGGGGGGGGGGCGGGGGGGGG?EGGGGFGGGGGGFGFGGGGFFGGGGGGGGGG
CCCCCGGGGGGGGGGGGGGGDEFGGGGGGGGGGGGGGGGGGGEGFFGGGGGGGGCFGGGGGGGGGGGGGFGGGFFGGGGGGGGGGGFGGGGGGGGGGGGGGGGFGEGGGGGGGGGFGGGGGGDFGGGEGGFGGGGGGDFGGGGGGGGGGG
@M06673:6:000000000-CMWK5:1:1101:13073:1006 1:N:0:1
@M06673:6:000000000-CMWK5:1:1101:13073:1006 2:N:0:1
NTCACGGCCTTCCTGTTGTGGTAATGAGGATTACTCGGATGTGAGTGTGTGACGATGCCACAGTAAATTTGATTAGTCGTGTGTAGAAAACTGTCAACCTATGCGTGCTACCGTGAATCTCGCGCAGTCGTGCGTAAGGGCCGAGGGCGA
CGGTCGCCCTCGGCCCTTACGCACGACTGCGCGAGATTCACGGTAGCACGCATAGGTTGACAGTTTTCTACACACGACTAATCAAATTTACTGTGGCATCGTCACACACTCACATCCGAGTAATCCTCATTACCACAACAGGAAGGCCGTG
+
+
#8-6A<FGEG<FEEGGGGGDGFC@FFDGGD<C@CE<FC7FFCECFECEFEGG,FCFDCFGG@CFCFDGEAF<FFGFFEFD,:@CE9EFGGGF,CF@CF@DFGFFCGGCDF6:4C<?=FECAFGCEEDGGGG7FECCEF8FF=FEG=FGC>
CCCCCGGGGGFEGEGE@@FEFEGGGEGGDGGGGDE:@ADDCFEFFGDE<F@F:FFGF<EEF9FF<CFFGG9DF@C=F>FFDGGGG9EGGGGDFF<FBFGBFGCDBAFBF8BB8FFGCE7+DAFFF9EFGGGGGGGGFFGGEDGGGCFFC>F
@M06673:6:000000000-CMWK5:1:1101:16647:1007 1:N:0:1
@M06673:6:000000000-CMWK5:1:1101:16647:1007 2:N:0:1
NTTCTCCCATTCACGACTGGCGATCTTGTATTACTCGGATGTGAGTGTGTGACGATGCCACAGTAAATTTGATTAGTCGTGTGAAGAAAACTGTCAACCTATGCGTGCTACCGTGAATCTCGCGCTTTGGTGAGCGTTCCCTAACTTTTCA
ACTGAAAAGTTAGGGAACGCTCACCAAAGCGCGAGATTCACGGTAGCACGCATAGGTTGACAGTTTTCTTCACACGACTAATCAAATTTACTGTGGCATCGTCACACACTCACATCCGAGTAATACAAGATCGCCAGTCGTGAATGGGAGA
+
+
#8ABCFFFGGGGGFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGEFGGGGGGGGGGGGGGGGGFFEEFFFEGGGDFGF
@CCC<FGFGFCGGGGCFFCGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGFGGGGGGGGGGGGGGGGGGGGGGDDFGGGGGGGGGGGGGGFGGGAFGGGG@FGG?BFEGGGFGFGGGGGGGG7FFGFFEGGGGGGGGFGD
@M06673:6:000000000-CMWK5:1:1101:12742:1007 1:N:0:1
@M06673:6:000000000-CMWK5:1:1101:12742:1007 2:N:0:1
NACAAAGAAACGCGGCACAGAATGTTTATAGGTCTGTTGAACACGACCAGAAAACTGGCCTAACGACGTTTGGTCAGTTCCATCAACATCATAGCCAGATGCCCAGAGATTAGAGCGCATGACAAGTAAAGGACGGTTGTCAGCGTCATAA
TTAATCAAGATGATGCTCGTTATGGTTTCCGTTGCTGCCATCTCAAAAACATTTGGACTGCTCCGCTTCCTCCTGAGACTGAGCTTTCTCGCCAAATGACGACTTCTACCACATCTATTGACATTATGGGTCTGCAAGCTGCTTATGCTAA
+
+
#8ACCGGGGGGGGGGGGGGGGGGGGGGGGGGGFGFGGGFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGCGGGGGGGGFGGGGGGGGGGGGGGGGGFGGGGAEFGGGGGGGGGGGGGGCFGGGGGGGGGGGFGGGGGGGGGGGGGG
CCCCCGGGGGGGFGGGFGGGFEGGFGGDGGGGGGGGGGGGGGGGGEFG<FFGGGGGCCFGGGGEGEGGGFEGGGGGGFGGGGGFGGGGGGDG@C@FFFE<:?FGGGGGFFGFGCGGFGGFGGGFGGGGGGGGGGFGFGGGGFFGGGGFGFF
@M06673:6:000000000-CMWK5:1:1101:15077:1007 1:N:0:1
@M06673:6:000000000-CMWK5:1:1101:15077:1007 2:N:0:1
NCTTGGACCTACGGGGGCGAGTTGAGCATATTACTCGGATGTGAGTGTGTGACGATGTAGGTTCGAGAACTGACCTTAAACCAATGTACAGGGATACCCTATGCGTGCTACCGTGAATCTCGCGCTATATATAGGGCCCATTTAATATATT
GAAATATATTAAATGGGCCCTATATATAGCGCGAGATTCACGGTAGCACGCATAGGGTATCCCTGTACATTGGTTTAAGGTCAGTTCTCGAACCTACATCGTCACACACTCACATCCGAGTAATATGCTCAACTCGCCCCCGTAGGTCCAA
+
+
#8BCCGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGCGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGFFGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
CCCCCGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
@M06673:6:000000000-CMWK5:1:1101:20943:1008 1:N:0:1
@M06673:6:000000000-CMWK5:1:1101:20943:1008 2:N:0:1
NTTTCATTGCGTACACTATTTCGCAGTGAATTCAGAAGATGTGAGTGTGTGACGATGCCTATGCGTGCTACCGTGAATCTCGCGCGCACCCGGGCTAACCTCCTCAGTAACCTAGATCGGAAGAGCACACGTCTGAACTCCAGTCACCGG
AGGTTACTGAGGAGGTTAGCCCGGGTGCGCGCGAGATTCACGGTAGCACGCATAGGCATCGTCACACACTCACATCTTCTGAATTCACTGCGAAATAGTGTACGCAATGAAAGAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGAT
+
+
#8ACCGGGGGGGGGGGGGGGGGGGGGGGGGGFGGGGGGGGGGGGGGGGGGGGGGGFFGGGGGGGGGEGGGGGGGGFGGGDGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGFGGGGGGFGGGGGGGGGGGGGGGGGGGGGGGGGG
CCCBCGGGGFGGGGGGGGGGGGGGGGGGGGGGGGGDGEFFGGGGGGGGGGGGGGGGGGGGGGGDGFGGGGGGGGGGGGGGGGGGGGGGGGGGEGGGGGFGGGGGGGGEGGGGGDGGGGGGGGGGGGGFGGGGGGGGEEDDGFGGGGGFFG
@M06673:6:000000000-CMWK5:1:1101:15049:1008 1:N:0:1
@M06673:6:000000000-CMWK5:1:1101:15049:1008 2:N:0:1


from itertools import islice,zip_longest

for i in zip_longest([1,2],[]):
    print(i)
tuple(i for i in range(4))
f1 = "/Users/hui/Desktop/exp46_30-217785519/20190412_S1_R1_001.fastq"
f2 = "/Users/hui/Desktop/exp46_30-217785519/20190412_S1_R2_001.fastq"

def fgen(f1,f2):
    f= open(f1,'rt')
    for fw,fs,  in zip(islice(f, 1, None, 2), islice(f, 1, None, 2), ):
        fw=fw.strip()
            # if line == reverse_comp(rev):
               # self.revcomp+=1
        yield fw,fs
    f.close()
g = fgen(f1,f2)
for _ in g:
    continue
_

for i in zip_longest(islice([1,2,3],1,None,1),islice([],1,None,1)):
    print(i)


next(g)


a='a'
b=None

if a or b:
    print(a,b)
else:
    print('here')


from collections import Counter

a = Counter()

a['a']=3
a['b']=2
a['c']=5
a.most_common(100)


"{:<9}".format(4)

from datetime import datetime
datetime.now().strftime('%Y/%m/%d %H:%M')
